config/routes.rb
Ensnare::Engine.routes.draw do

  get "dashboard/metrics", to: "dashboard#metrics", :as=> 'metrics'
  get "dashboard/mode", to: "dashboard#mode", :as=> 'mode'
  get "dashboard/configuration", to: "dashboard#configs", :as=> 'configs'
  get "dashboard/edit"
  get "dashboard/violations", to: "dashboard#violations"
  
  root to: "violations#redirect", :as=>:redir
  match "violations/captcha", to: "violations#captcha", :as => 'captcha'
  
  post "configuration/change_mode", to: "configuration#change_mode", as: 'change_mode'
  
end

app/models/ensnare/violation.rb
module Ensnare
  class Violation < ActiveRecord::Base
    attr_accessible :ip_address, :violation_type, :session_id, :user_id, :expected, :observed, :name, :weight

  end
end

app/controllers/ensnare/application_controller.rb
module Ensnare
  class ApplicationController < ActionController::Base
    before_filter :check_privileges

    def check_privileges
      
      if(Ensnare.dashboard_user_method.present? && Ensnare.dashboard_authorization_method.present?)
        user = send(Ensnare.dashboard_user_method)
        is_admin = user.try(:send,Ensnare.dashboard_authorization_method)
        
        if(is_admin != true)

          Rails.logger.error "Unauthorized access attempt: Configure dashboard access with Ensnare.dashboard_user_method option."
          raise ActionController::RoutingError.new('Not Found')
        end
      else
        Rails.logger.error "Dashboard access requires configuration of Ensnare.dashboard_user_method option"
        raise ActionController::RoutingError.new('Not Found')
      end
    end
  end
end

app/controllers/ensnare/configuration_controller.rb
require_dependency "ensnare/application_controller"

module Ensnare
  class ConfigurationController < ApplicationController
  layout 'ensnare/dashboard'

    def change_mode
      if( %w[enforce disabled log].include?(params[:mode]))
        Ensnare.mode = params[:mode].to_sym
      end

      redirect_to mode_path
    end

  end
end

app/controllers/ensnare/dashboard_controller.rb
require_dependency "ensnare/application_controller"

module Ensnare
  class DashboardController < ApplicationController
    layout 'ensnare/dashboard'
    
    def mode
      #render mode erb, read config file and toggle switches
      @mode = Ensnare.mode
      @timer = Ensnare.global_timer
    end

    def metrics
      #@violations = Ensnare::Violation.where("created_at >= ?", Time.now-Ensnare.global_timer.seconds)
      @violations = Ensnare::Violation.all

      @violations_by_type= Ensnare::Violation.group(:violation_type).limit(params[:limit]||25).offset(params[:offset]||0).count(:order=>"count_all desc")
      @violations_by_ip = Ensnare::Violation.group(:ip_address).limit(params[:limit]||25).offset(params[:offset]||0).count(:order=>"count_all desc")
      @violations_by_session = Ensnare::Violation.group(:session_id).limit(params[:limit]||25).offset(params[:offset]||0).count(:order=>"count_all desc")
      @violations_by_user_id = Ensnare::Violation.group(:user_id).limit(params[:limit]||25).offset(params[:offset]||0).count(:order=>"count_all desc")

    end

    def configs
      @timer = Ensnare.global_timer
    end

    def violations
      @violations = Ensnare::Violation.order("created_at DESC").limit(100)
    end


  end
end

app/controllers/ensnare/violations_controller.rb
require_dependency "ensnare/application_controller"



module Ensnare
  class ViolationsController < ApplicationController
    before_filter :ensnare, :only=>:routing_error
    skip_before_filter :check_privileges
    layout 'ensnare/application'

    def redirect
      redirect_to redir_url(:id=>Random.rand(1000000))
    end

    def captcha
      respond_to do |format|
        if verify_recaptcha
          session[:ensnare] ||= {}
          session[:ensnare][:captcha_solved] = true
          redirect_to main_app.root_url
          return
        else
          format.html { render :layout=> 'ensnare/captcha' }
        end
      end
    end


    def routing_error

      raise ActionController::RoutingError.new('Not Found')
    end



  end
end

app/helpers/ensnare/application_helper.rb
module Ensnare
  module ApplicationHelper
  end
end

app/helpers/ensnare/dashboard_helper.rb
module Ensnare
  module DashboardHelper
    

  end
end

app/helpers/ensnare/violation_helper.rb
module Ensnare
  module ViolationHelper
  end
end

app/views/ensnare/dashboard/edit.html.erb
<h1>Dashboard#edit</h1>
<p>Find me in app/views/ensnare/dashboard/edit.html.erb</p>

app/views/ensnare/dashboard/metrics.html.erb
<div class="container">
    <div class="row">
      <div class="span12">
          <% if Ensnare.error_message.present? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= Ensnare.error_message %>
        </div>
        <% end %>
        <% if Ensnare.warning_message.present? %>
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= Ensnare.warning_message %>
        </div>
        <% end %>
        <h2>Metrics</h2><br>
        <div class="well">
            <h3>Basic</h3>
            <dl class="dl-horizontal">
                <dt>Violation Count:</dt>
                <dd><%= @violations.count %></dd>
                <dt>Unique IPs:</dt>
                <dd><%= @violations_by_ip.count %></dd>
                <dt>Unique Sessions:</dt>
                <dd><%= @violations_by_session.count %></dd>
            </dl>

            <%= render :partial=>'ensnare/dashboard/metrics/table', :locals=>{:title=>"Violation Type", :objects=>@violations_by_type} %>

            <%= render :partial=>'ensnare/dashboard/metrics/table', :locals=>{:title=>"IP Address", :objects=>@violations_by_ip} %>

            <%= render :partial=>'ensnare/dashboard/metrics/table', :locals=>{:title=>"Session ID", :objects=>@violations_by_session} %>

            <%= render :partial=>'ensnare/dashboard/metrics/table', :locals=>{:title=>"User ID", :objects=>@violations_by_user_id} %>

        </div>
    </div>
</div>

app/views/ensnare/dashboard/metrics/_table.html.erb
<h3><%= title %></h3>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Count</th>
        </tr>
    </thead>
    <tbody>
        <% objects.each do |key, value| %>
        <tr>
            <td><%= key.blank? ? "<blank>" : key %></td>
            <td><%= value %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/ensnare/dashboard/mode.html.erb
</div><!--/.nav-collapse -->
</div>
</div>
</div>
</div>

<div class="container">
  <div class="row">
    <div class="span6">
      <% if Ensnare.error_message.present? %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>

        <%= Ensnare.error_message %>
      </div>
      <% end %>
      <% if Ensnare.warning_message.present? %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>

        <%= Ensnare.warning_message %>
      </div>
      <% end %>
      <% if @mode == :enforce %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Ensnare is in <strong>'Enforce'</strong> mode.
      </div>
      <% elsif @mode == :log %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Ensnare is in <strong>'Log Only'</strong> mode.
      </div>
      <% elsif @mode == :disabled %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Ensnare is in <strong>'Disabled'</strong> mode.
      </div>
      <% end %>
      <h2>Ensnare Setup</h2><br>
      <div class="alert hidden" id="error_display">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Invalid settings or server is down!</strong>
      </div>
      <div class="well">
        These changes are not persistent.  Edit "ensnare.rb" config file for persistent changes.
        <hr>
        <%= form_tag change_mode_url do %>

        <div class="control-group">
          <div class="options">
            <label>
              <input type="radio" name="mode" id="disabled" value="disabled">
              Disabled.
            </label>
          </div>
          <div class="options">
            <label>
              <input type="radio" name="mode" id="log" value="log">
              Log only mode.
            </label>
          </div>
          <div class="options">
            <label>
              <input type="radio" name="mode" id="enforce" value="enforce">
              Enforce.
            </label>
          </div>
        </br>
        <%= submit_tag "Submit Settings", :class => "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ensnare/dashboard/violations.html.erb
<table class="table">
    <thead>
        <tr>
            <th>Event Time</th>
            <th>Weight</th>
            <th>IP Address</th>
            <th>Session Id</th>
            <th>User Id</th>
            <th>Type</th>
            <th>Name</th>
            <th>Expected Value</th>
            <th>Observed Value</th>
        </tr>
    </thead>
    <tbody>
    <% @violations.each do |v| %>
        <tr>
            <td><%= v.created_at.to_s %></td>
            <td><%= v.weight.to_s %></td>
            <td><%= v.ip_address.to_s %></td>
            <td><%= v.session_id.to_s %></td>
            <td><%= v.user_id.to_s %></td>
            <td><%= v.violation_type.to_s %></td>
            <td><%= v.name.to_s %></td>
            <td><%= v.expected.to_s %></td>
            <td><%= v.observed.to_s %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/ensnare/violations/captcha.html.erb
<h1>Uh oh!</h1>
<% if(request.post?) %>
    <p class="text-error">Unable to validate your response. Please try again.</p>
<% end %>
<p>Something has gone wrong. Please confirm you are human.<p>
<%= form_tag captcha_path do  %>
    <%= recaptcha_tags %>
    <%= submit_tag %>
<% end %>

app/views/ensnare/violations/redirect.html.erb
<h1>Violation#redirect</h1>
<p>Find me in app/views/ensnare/violation/redirect.html.erb</p>

app/views/ensnare/violations/show.html.erb
Sorry, it appears that you are a nasty hacker. 
<br/>

app/views/layouts/ensnare/application.html.erb
<%= yield %>

app/views/layouts/ensnare/captcha.html.erb
<!DOCTYPE html>
<!-- saved from url=(0060)http://getbootstrap.com/2.3.2/examples/starter-template.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<title><%= content_for?(:title) ? yield(:title) : "Ensnare" %></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag "ensnare/application", :media => "all" %>
    <%= javascript_include_tag "ensnare/application" %>

<!-- <link rel="stylesheet" href="css/bootstrap-switch.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="js/bootstrap-switch.js"></script>

<script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/1.7/bootstrap-switch.min.js"> </script>
<link href="css/bootstrap.css" rel="stylesheet">
<link rel="stylesheet" href="css/toggle-switch.css"> -->
<style>
body {
  padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
}
</style>



<!-- Fav and touch icons -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
</head>

    <body>
        <%= yield %>
    </body>
</html>

app/views/layouts/ensnare/dashboard.html.erb
<!DOCTYPE html>
<!-- saved from url=(0060)http://getbootstrap.com/2.3.2/examples/starter-template.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<title><%= content_for?(:title) ? yield(:title) : "Ensnare" %></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Ensnare">
<meta name="author" content="Andy Hoernecke and Scott Behrens">

    
    <%= stylesheet_link_tag "ensnare/application", :media => "all" %>
    <%= javascript_include_tag "ensnare/application" %>

<style>
body {
  padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
}
</style>



<!-- Fav and touch icons -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
</head>

<body>

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">

        <a class="brand" href="http://getbootstrap.com/2.3.2/examples/starter-template.html#">Ensnare</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
             <li class=""><%= link_to('Mode', mode_path)  %>  </li>
             <li class=""><%= link_to('Configuration', configs_path)  %>  </li>
             <li class=""><%= link_to('Metrics', metrics_path)  %>  </li>
             <li class=""><%= link_to('Violations', dashboard_violations_path) %> </li>
             <li class=""></li>

         </ul>
         <div class="pull-right">
<% if Ensnare.mode == :enforce %>
<button type="button" class="btn btn-success disabled" id="activated" value="Save">
  <span class="glyphicon icon-thumbs-up" id="iconed"> Ensnare Activated</span>
  <% elsif Ensnare.mode == :log %>
  <button type="button" class="btn btn-warning disabled" id="activated" value="Save">
    <span class="glyphicon icon-pencil" id="iconed"> Log Only</span>
    <% elsif Ensnare.mode == :disabled %>
    <button type="button" class="btn btn-danger disabled" id="activated" value="Save">
     <span class="glyphicon icon-thumbs-down" id="iconed"> Ensnare Disabled</span>
     <% end %>
          </button>
      </div>
  </div><!--/.nav-collapse -->
</div>
</div>
</div>
</div>
        <%= yield %>
</body></html>